#!/usr/bin/env zsh
set -eu

lines=("# This file was generated by '${0:t}'.")
lines+=('')
for tap in "${(@f)$(brew tap)}"; do
  lines+=("tap \"${tap}\"")
done
lines+=('')
for formula in "${(@f)$(brew list --formulae --full-name --installed-on-request)}"; do
  lines+=("brew \"${formula}\"")
done
lines+=('')
lines+=('cask_args appdir: "/Applications"')
for cask in "${(@f)$(brew list --casks)}"; do
  lines+=("cask \"${cask}\"")
done

printf '%s\n' "${lines[@]}"
